#!/bin/bash
source _common.sh
ynh_abort_if_errors

ynh_config_change_url_nginx
nexora_render_nginx_conf "/etc/nginx/conf.d/${new_domain}.d/${app}.conf"
nginx -t && systemctl reload nginx
nexora_restart_services
